
# –ö–æ–º–∞–Ω–¥—ã:
# /soundloop <–∏–≥—Ä–æ–∫> <–∑–≤—É–∫> <–¥–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å_–∑–≤—É–∫–∞> <—Å–∫–æ–ª—å–∫–æ_—Ä–∞–∑_–µ–≥–æ_–∏–≥—Ä–∞—Ç—å> # xcore.admin
# /stopsound <–∏–≥—Ä–æ–∫> - –û—Å—Ç–∞–Ω–æ–≤–∏—Ç—å –≤—Å–µ –∑–≤—É–∫–∏ –∏–≥—Ä–æ–∫—É # xcore.admin

# MYSQL / SQLITE
use-database: SQLITE
database:
  host: localhost
  port: 3306
  database: dsfsdfsd
  user: user
  password: password

messages:
  no-permission: '&e‚åö &7‚Çé‚à´ &f–£ –≤–∞—Å –Ω–µ—Ç –¥–æ—Å—Ç—É–ø–∞ –∫ —ç—Ç–æ–π –∫–æ–º–∞–Ω–¥–µ.'
  player-null: '&e‚åö &7‚Çé‚à´ &f–ò–≥—Ä–æ–∫ –Ω–µ –Ω–∞–π–¥–µ–Ω!'
  arg-unknown: '&e‚åö &7‚Çé‚à´ &f–û–¥–∏–Ω –∏–∑ –∞—Ä–≥—É–º–µ–Ω—Ç–æ–≤ –Ω–µ —Ä–∞—Å–ø–æ–∑–Ω–∞–Ω. –ü—Ä–æ–≤–µ—Ä—å—Ç–µ –≤—Å–µ –ª–∏ —Å—Ç—Ä–æ–∫–∏ - —Å—Ç—Ä–æ–∫–∏, –∏ –≤—Å–µ –ª–∏ —á–∏—Å–ª–∞ - —á–∏—Å–ª–∞.'
  playsound: '&e‚åö &7‚Çé‚à´ &f–ó–≤—É–∫ –≤–∫–ª—é—á–µ–Ω –∏–≥—Ä–æ–∫—É &e%s'
  stopsound: '&e‚åö &7‚Çé‚à´ &f–ó–≤—É–∫ –æ—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω –∏–≥—Ä–æ–∫—É &e%s'

  # Usage
  soundloop-usage: '&e‚åö &7‚Çé‚à´ &e/soundloop <–∏–≥—Ä–æ–∫> <–∑–≤—É–∫> <–¥–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å_–∑–≤—É–∫–∞> <—Å–∫–æ–ª—å–∫–æ_—Ä–∞–∑_–µ–≥–æ_–∏–≥—Ä–∞—Ç—å>'
  stopsound-usage: '&e‚åö &7‚Çé‚à´ &e/stopsound <–∏–≥—Ä–æ–∫>'

# Anti-Void System
void-tp:
  commandPlayer: '' #–∫–æ–º–∞–Ω–¥–∞ –æ—Ç –∏–≥—Ä–æ–∫–∞, none - –Ω–∏–∫–∞–∫–∞—è
  commandConsole: 'spawn %player_name%' #–∫–æ–º–∞–Ω–¥–∞ –æ—Ç –∫–æ–Ω—Å–æ–ª–∏, '' - –Ω–∏–∫–∞–∫–∞—è
  worlds:
    - 'spawn'
    - 'govno_world'

# Broadcast System
broadcast:
  no-message: '&c‚åö &7‚Çé‚à´ &f–ù–µ–ª—å–∑—è &c–æ—Ç–ø—Ä–∞–≤–∏—Ç—å&f –ø—É—Å—Ç–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ!'
  chat-broadcast:
    settings:
      sound: ENTITY_ENDERMAN_TELEPORT
      cooldown: 60 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
      permission: acore.cbroad
      limit: 70 # —Å–∏–º–≤–æ–ª–æ–≤
    messages:
      no-permission: '&c‚åö &7‚Çé‚à´ &f–ù–µ–æ–±—Ö–æ–¥–∏–º –¥–æ–Ω–∞—Ç –æ—Ç &r%acore_magma%&f –∏ –≤—ã—à–µ! &7(/donate)'
      help: '&c‚åö &7‚Çé‚à´ &f–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: &e/cbroad <—Ç–µ–∫—Å—Ç>'
      broad: '&b‚úé &7‚Çé‚à´ &f<message>'
      hover: '&b‚Üí &f–û—Ç–ø—Ä–∞–≤–∏—Ç–µ–ª—å: &b<name>'
  title-broadcast:
    settings:
      sound: ENTITY_ENDERMAN_TELEPORT
      cooldown: 60 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
      permission: acore.tbroad
      limit: 15;15 #—Å–∏–º–≤–æ–ª–æ–≤ —Å–≤–µ—Ä—Ö—É;—Å–Ω–∏–∑—É
    messages:
      no-permission: '&c‚åö &7‚Çé‚à´ &f–ù–µ–æ–±—Ö–æ–¥–∏–º –¥–æ–Ω–∞—Ç –æ—Ç &r%acore_super%&f –∏ –≤—ã—à–µ! &7(/donate)'
      help: '&c‚åö &7‚Çé‚à´ &f–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: &e/tbroad <—Ç–µ–∫—Å—Ç —Å–≤–µ—Ä—Ö—É>%newline%<—Ç–µ–∫—Å—Ç —Å–Ω–∏–∑—É>'
      up-broad: '<message>'
      down-broad: '<message>'
  all-broadcast:
    settings:
      sound: ENTITY_ENDERMAN_TELEPORT
      cooldown: 60 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
      permission: acore.abroad
      limit: 70
    messages:
      no-permission: '&c‚åö &7‚Çé‚à´ &f–ù–µ–æ–±—Ö–æ–¥–∏–º –¥–æ–Ω–∞—Ç –æ—Ç &r%acore_govnoed%&f –∏ –≤—ã—à–µ! &7(/donate)'
      help: '&c‚åö &7‚Çé‚à´ &f–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: &e/abroad <—Ç–µ–∫—Å—Ç>'
      broad: '&b‚úé &7‚Çé‚à´ &f<message>'
      up-broad: '&c‚Üë &c&l–û–ë–™–Ø–í–õ–ï–ù–ò–ï &c‚Üë'
      down-broad: '&f–û–±—ä—è–≤–ª–µ–Ω–∏–µ –≤ —á–∞—Ç–µ!'
      hover: '&b‚Üí &f–û—Ç–ø—Ä–∞–≤–∏—Ç–µ–ª—å: &b<name>'

# Join System

join:
  sound: ENTITY_FIREWORK_ROCKET_LAUNCH
  motd: # –≤ —á–∞—Ç –∏–≥—Ä–æ–∫—É –ø—Ä–∏ –≤—Ö–æ–¥–µ
    - '&r'
    - '&r                &6&l‚óú      &#e9d75a&l·¥Ä&#e9cc5e&lÍú±&#eac062&l&n·¥õ&#eab567&l&n·¥è&#eaaa6b&l&n Ä&#eb9e6f&l…™&#eb9373&lÍú±      &6&l‚óù'
    - '&r'
    - '&r                &a–ú—ã —Ä–∞–¥—ã –≤–∞—Å –≤–∏–¥–µ—Ç—å ‚ò∫'
    - '&r'
    - '&r               &f–ù–∞—à —Å–∞–π—Ç: &6www.astoris.ru'
    - '&r          &f–ù–∞—à–∞ –≥—Ä—É–ø–ø–∞ –í–ö: &6vk.com/astorismc'
    - '&r         &f–ù–∞—à –¥–∏—Å–∫–æ—Ä–¥: &6discord.gg/ebwT8m3ucG'
    - '&r'
    - '&r             &6&l‚óü   &8‚Äπ‚Äπ &f–ü—Ä–∏—è—Ç–Ω–æ–π –∏–≥—Ä—ã! &8‚Ä∫‚Ä∫    &6&l‚óû'
    - '&r'
  new-player: [ '&cü™ì &7‚Çé‚à´ &f–ù–æ–≤—ã–π —É–±–∏–π—Ü–∞ &c<player> &f–≤–ø–µ—Ä–≤—ã–µ –≤–æ—à–µ–ª –Ω–∞ —Ä–µ–∂–∏–º!' ] #–ø–µ—Ä–≤—ã–π –≤—Ö–æ–¥

# protect System

protect:
  admins: #–Ω—É–∂–Ω–æ –≤–≤–æ–¥–∏—Ç—å –ø–∞—Å –ø—Ä–∏ –≤—Ö–æ–¥–µ, –µ—Å–ª–∏ —É —á–µ–ª–∞ –æ–ø–∫–∞/* –ø–æ—è–≤–ª—è–µ—Ç—Å—è - –µ–≥–æ –∫–∏–∫–∞–µ—Ç (–µ—Å–ª–∏ –æ–Ω –≤–Ω–µ —ç—Ç–æ–≥–æ —Å–ø–∏—Å–∫–∞)
    - 'x7lare'
    - '_m0rph3us'
  admin-pass-code: '$ClW8NY8N$k~' # –≤–≤–µ—Å—Ç–∏ /pass <–∫–æ–¥> –¥–ª—è –≤—Ö–æ–¥–∞, –∏–Ω–∞—á–µ –∫–∏–∫
  kick-message: '&c&l–û–ë–•–û–î –ó–ê–©–ò–¢–´'
  spam-message: '&büõ° &7‚Çé‚à´ &f–ò—Å–ø–æ–ª—å–∑—É–π—Ç–µ &a/pass <–∫–æ–¥> &f–¥–ª—è –≤—Ö–æ–¥–∞ –Ω–∞ —Å–µ—Ä–≤–µ—Ä.'

# Prefix system
# Format: %xcore_magma%, %xcore_super%

prefixes:
  default: ''

# Donators system

donators:
  broadcasts: #—Å–æ–æ–±—â–µ–Ω–∏–µ –æ –ø–æ–∫—É–ø–∫–µ –¥–æ–Ω–∞—Ç–∞
    settings:
      permission: acore.bypass
      sound: ENTITY_FIREWORK_ROCKET_LAUNCH
    dbroad: #–∫–æ–º–∞–Ω–¥–∞ —Ñ–æ—Ä–º–∞—Ç–∞ /dbroad <–Ω–∏–∫> <–¥–æ–Ω–∞—Ç –≤ –∫—Ñ–≥>
      chorus:
        - ''
        - '&f –ï–±–ª–∞–Ω—á–∏–∫ <player> –∫—É–ø–∏–ª %acore_chorus%&f –∏ –±—ã–ª –∑–∞—Å–∫–∞–º–ª–µ–Ω!'
        - '&f –°–æ—Å–∏ —Ö—É–π –ø–æ–∫–∞ –Ω–µ –ø–æ–∑–¥–Ω–æ - &eastoris.ru'
        - ''
      magma:
        - ''
        - '&f –ï–±–ª–∞–Ω—á–∏–∫ <player> –∫—É–ø–∏–ª %acore_magma%&f –∏ –±—ã–ª –∑–∞—Å–∫–∞–º–ª–µ–Ω!'
        - '&f –°–æ—Å–∏ —Ö—É–π –ø–æ–∫–∞ –Ω–µ –ø–æ–∑–¥–Ω–æ - &eastoris.ru'
        - ''

  # –û—Ç–∫–ª—é—á–∞–µ—Ç—Å—è –≤ –ü–í–ü, —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª –µ—â–µ –±—É–¥–µ—Ç –¥–æ–ø–∏—Å—ã–≤–∞—Ç—å—Å—è
  commands:
    tempfly: # –≤—Ä–µ–º–µ–Ω–Ω—ã–π –ø–æ–ª–µ—Ç –¥—Ä—É–≥—É
      settings:
        permission: acore.tempfly
        time: 180 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
        cooldown: 600 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
      messages:
        usage: '&e‚åö &7‚Çé‚à´ &f–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: &e/tempfly <–Ω–∏–∫>'
        to-friend: '&b‚åõ &7‚Çé‚à´ &f–í—ã &a—É—Å–ø–µ—à–Ω–æ&f –≤—ã–¥–∞–ª–∏ –ø–æ–ª–µ—Ç –∏–≥—Ä–æ–∫—É!'
        offline: '&a‚åõ &7‚Çé‚à´ &f–≠—Ç–æ—Ç &a–∏–≥—Ä–æ–∫&f —Å–µ–π—á–∞—Å –æ—Ñ—Ñ–ª–∞–π–Ω.'
        cooldown: '&a‚åõ &7‚Çé‚à´ &f–ü–æ–¥–æ–∂–¥–∏—Ç–µ, –≤—ã &a–≤—ã–¥–∞–≤–∞–ª–∏&f –ø–æ–ª—ë—Ç —Ä–∞–Ω–µ–µ.'
        accept-friend: '&b‚åõ &7‚Çé‚à´ &f–ò–≥—Ä–æ–∫ &b<player> &f–≤—ã–¥–∞–ª –≤—Ä–µ–º–µ–Ω–Ω—ã–π –ø–æ–ª—ë—Ç!'
        reminder-msg: '&c‚åõ &7‚Çé‚à´ &f–î–æ –∫–æ–Ω—Ü–∞ &c–ø–æ–ª—ë—Ç–∞&f –æ—Å—Ç–∞–ª–æ—Å—å &c<time>'
        reminder: #–Ω–∞–ø–æ–º–∏–Ω–∞–Ω–∏–µ —á—Ç–æ —Ñ–ª–∞–π –∫–æ–Ω—á–∞–µ—Ç—Å—è
          - '120'
          - '60'
          - '30'
          - '10'
    tempgod: #–≤—Ä–µ–º–µ–Ω–Ω–æ–µ –±–µ—Å—Å–º–µ—Ä—Ç–∏–µ –¥—Ä—É–≥—É
      settings:
        permission: acore.tempgod
        time: 180 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
        cooldown: 600 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
      messages:
        usage: '&e‚åö &7‚Çé‚à´ &f–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: &e/tempgod <–Ω–∏–∫>'
        to-friend: '&b‚åõ &7‚Çé‚à´ &f–í—ã &a—É—Å–ø–µ—à–Ω–æ&f –≤—ã–¥–∞–ª–∏ –±–µ—Å—Å–º–µ—Ä—Ç–∏–µ –∏–≥—Ä–æ–∫—É!'
        offline: '&a‚åõ &7‚Çé‚à´ &f–≠—Ç–æ—Ç &a–∏–≥—Ä–æ–∫&f —Å–µ–π—á–∞—Å –æ—Ñ—Ñ–ª–∞–π–Ω.'
        cooldown: '&a‚åõ &7‚Çé‚à´ &f–ü–æ–¥–æ–∂–¥–∏—Ç–µ, –≤—ã &a–≤—ã–¥–∞–≤–∞–ª–∏&f –±–µ—Å—Å–º–µ—Ä—Ç–∏–µ —Ä–∞–Ω–µ–µ.'
        accept-friend: '&b‚åõ &7‚Çé‚à´ &f–ò–≥—Ä–æ–∫ &b<player> &f–≤—ã–¥–∞–ª –≤—Ä–µ–º–µ–Ω–Ω–æ–µ –±–µ—Å—Å–º–µ—Ä—Ç–∏–µ!'
        reminder-msg: '&c‚åõ &7‚Çé‚à´ &f–î–æ –∫–æ–Ω—Ü–∞ &c–±–µ—Å—Å–º–µ—Ä—Ç–∏—è&f –æ—Å—Ç–∞–ª–æ—Å—å &c<time>'
        reminder: #–Ω–∞–ø–æ–º–∏–Ω–∞–Ω–∏–µ —á—Ç–æ –±–µ—Å—Å–º–µ—Ä—Ç–∏–µ –∫–æ–Ω—á–∞–µ—Ç—Å—è
          - '120'
          - '60'
          - '30'
          - '10'

# Newbiefilter system

newbie-filter:
  settings:
    time-to-chat: 300 #–≤ —Å–µ–∫—É–Ω–¥–∞—Ö
    no-sound: ENTITY_VILLAGER_NO
  messages:
    waiting: '&b‚åö &7‚Çé‚à´ &f–ü–æ–¥–æ–∂–¥–∏—Ç–µ &e<time> &f–ø–µ—Ä–µ–¥ —Ç–µ–º, –∫–∞–∫ –ø–∏—Å–∞—Ç—å –≤ —á–∞—Ç.'

# Automessage system

auto-message:
  settings:
    random: true # true/false - —Å–æ–æ–±—â–µ–Ω–∏—è —Ä–∞–Ω–¥–æ–º–Ω–æ –∏–∑ —Å–ø–∏—Å–∫–∞ –∏–ª–∏ –Ω–µ—Ç
    time: 2000 # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
  messages:
    m1:
      - ''
      - '&e‚åõ &7‚Çé‚à´ &f–ù–µ –∑–∞–±—ã–≤–∞–π &e&n–∑–≤–∞—Ç—å&f —Å–≤–æ–∏—Ö –¥—Ä—É–∑–µ–π!'
      - '&f      –í–º–µ—Å—Ç–µ –≤–µ—Å–µ–ª–µ–µ! &e&nmc.astoris.ru'
      - ''


modules:
  board: true
  npc: true
  void-tp: true
  join: true
  broadcast: true
  donators: true
  auto-message: true
  newbie: true
  ignore: true

ignore:
  messages:
    ignored: '&e‚åö &7‚Çé‚à´ &f–í—ã –Ω–µ –º–æ–∂–µ—Ç–µ –Ω–∞–ø–∏—Å–∞—Ç—å —ç—Ç–æ–º—É –∏–≥—Ä–æ–∫—É!'
    add: '&e‚åö &7‚Çé‚à´ &f–í—ã –¥–æ–±–∞–≤–∏–ª–∏ –∏–≥—Ä–æ–∫–∞ &a<player> &f–≤ —á—Å.'
    remove: '&e‚åö &7‚Çé‚à´ &f–í—ã —É–±—Ä–∞–ª–∏ –∏–≥—Ä–æ–∫–∞ &a<player> &f–∏–∑ —á—Å.'
    list: '&e‚åö &7‚Çé‚à´ &f–í–æ—Ç –≤–∞—à —á–µ—Ä–Ω—ã–π —Å–ø–∏—Å–æ–∫: &a<players>'

board:
  pages:
    - board1
    - board2
  switch-time: 7